### ISSUE TITLE
No settings Available 

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#21]
No option to enable or disable dark theme in app

**Comment by sunny52525** [comment]
I can work on this

**Comment by ritwikshanker** [comment]
> I can work on this
Ok. I'll then assign this issue to you!

**Comment by sunny52525** [comment]
> > I can work on this
> 
> Ok. I'll then assign this issue to you!

So I need to add a complete new page or just a Menu option would work?(since there is only one option,I dont think a whole setting page is necessary)

**Comment by ritwikshanker** [comment]
> > > I can work on this
> > 
> > 
> > Ok. I'll then assign this issue to you!
> 
> So I need to add a complete new page or just a Menu option would work?(since there is only one option,I dont think a whole setting page is necessary)

Hi, Sorry for the late reply. I was actually thinking that we could add this option inside a three dot menu at the top right corner. Since I plan on adding more personalization option. Nonetheless the issue for now is resolved. I'll merge you code.

**Comment by sunny52525** [comment]
> Hi, Sorry for the late reply. I was actually thinking that we could add this option inside a three dot menu at the top right corner. 

That switch is a menu item. You can still more items in the menu and it should work fine.

**Comment by ritwikshanker** [comment]
> That switch is a menu item. You can still more items in the menu and it should work fine.

Yeah, I reviewed the code. It will not be a big of an issue.
