### ISSUE TITLE
Add a option to select/change default country

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#39]
The country which will be selected as default will always appear at the top of the list.

**Comment by Charis1331** [comment]
Hi @ritwikshanker,
From what I understand you want to persist the user selected country even after app/phone restart, right?

**Comment by ritwikshanker** [comment]
> Hi @ritwikshanker,
> From what I understand you want to persist the user selected country even after app/phone restart, right?
> If so, can I get assigned this?

Yes. Storing it in shared preference. But user can always change his default country, whenever he wants. 
Sure, I will assign this issue to you.

**Comment by Charis1331** [comment]
Please check #43 and let me know what you think. Thanks.
