### ISSUE TITLE
Add a better README.md

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#42]
- The current readme.md is very poor looking with no images and bad formatting.
- Repo doesn't have a good cover image too. 
- No app screenshots present
- demo.gif is of old version (I'll give you a new one)
- Merging contribution guidelines to project readme
- Adding Version Changelog to readme

**Comment by AkshaiBaruah** [comment]
Sir I would like to work on this Issue.
Also if it's okay then I would also like to add a guide to make PR for hacktoberfest at the end of readme

**Comment by ritwikshanker** [comment]
Sure @AkshaiBaruah 
I've assigned you this issue. For this, you can directly raise your PR to the `master` branch.

**Comment by AkshaiBaruah** [comment]
Can you provide me with the new demo.gif

**Comment by ritwikshanker** [comment]
Hey, @AkshaiBaruah Actually I had added the new gif a few months back when this issue went stale. You can use the current gif present in the readme.

**Comment by ritwikshanker** [comment]
@AkshaiBaruah Are you still working on this? If not I'll have to re assign the issue to someone else.

**Comment by gururani-abhishek** [comment]
great, would love to work on it.
