### ISSUE TITLE
XML to Jetpack Compose - Stay Home Tips Screen

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#56]

**Comment by hardiksachan** [comment]
Hey, if you don't mind, I'd like to work on this.

**Comment by ritwikshanker** [comment]
Sure. You can check out your branch from appVersion/6.x. That branch might be a bit unstable for now as we are undergoing major API changes. 
I'm assigning you the issue.

**Comment by hardiksachan** [comment]
I have implemented the UI using Jetpack Compose, please take a look!
