### ISSUE TITLE
XML to Jetpack Compose - About Screen

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#57]

**Comment by Kardelio** [comment]
Hey there, do you mind if I grab hold of this issue and give it a go?
I don't want to step on anyone else's toes though, so totally ok if not

**Comment by ritwikshanker** [comment]
> Hey there, do you mind if I grab hold of this issue and give it a go? I don't want to step on anyone else's toes though, so totally ok if not

Yes, you can go ahead. I'm assigning you this issue. Just raise the PR to `devlop` branch.

**Comment by Kardelio** [comment]
@ritwikshanker Thank you for that, ok ill make a PR to `develop` branch when done, thanks very much for letting me get involved, this looks like a really cool project btw :)

**Comment by ritwikshanker** [comment]
@Kardelio No problem. You might see that some parts of the code might be messy since when I first made it I was pretty new to Android Dev, so decided in this Hacktoberfest to refactor the code. Thanks for the help. ✌🏽

**Comment by Kardelio** [comment]
@ritwikshanker absolutely no worries at all matey, yeh i've seen most of what you described! Dont worry I got this ;)

Also P.S two questions:
1. How do you feel about me using proper MVVM architecture on this about screen?
2. How do you feel about me adding Hilt (Dagger Hilt) for dependency injection? Ill only use it on this about screen for now, but then it will at least be in the codebase... ?

**Comment by ritwikshanker** [comment]
1. For Sure, go ahead with it. Even I want a proper MVVM arch throughout the app. Already started working on it on my ticket.
2. I actually have very little experience with it. If you feel DI can be achieved, then do add it. I'll also learn something new. 🙂

**Comment by Kardelio** [comment]
@ritwikshanker Awesome!!! Consider both done in that case :) :)

**Comment by Kardelio** [comment]
FYI Just finished the Compose part of this work now, heres a progress screenshot...
On the left is the "old" AboutUsFragment and on the right is the new one written in Compose...

<img width="963" alt="Screenshot 2021-10-01 at 21 43 44" src="https://user-images.githubusercontent.com/10523656/135677822-4059cb9a-ab35-4752-bf11-06a763bd74e4.png">

Im going to now add the DI stuff and build the MVVM for this screen properly then ill PR 👍

**Comment by Kardelio** [comment]
Addressed in #62
