### ISSUE TITLE
Implement Loading and Error States throughout the app

### ISSUE THREAD

**Issue by ritwikshanker** [ritwikshanker/GoCoronaGo#64]
As of now, there is no way for the user to know what is happening unless the result is successful. 
Also in case of failure of API, an option for retry should be there.

**Comment by AkshaiBaruah** [comment]
Sir can I would like to work on this issue please assign this to me .

**Comment by ritwikshanker** [comment]
Sure @AkshaiBaruah. Raise the PR against `Devlop` branch for this
