### ISSUE TITLE
Hide Keyboard when clicked in the background 

### ISSUE THREAD

**Issue by cdhiraj40** [ritwikshanker/GoCoronaGo#70]
**Is your feature request related to a problem? Please describe.**

its always good to increase user experience and this feature does helps in it. 

**Describe the solution you'd like**
A hide keyboard method which will let keyboard when clicked in the background 

**Describe alternatives you've considered**
none

**Additional context**
as you can see it becomes hard to see the texts and user has to go all the way down to click on back.

https://user-images.githubusercontent.com/75211982/136253622-f2f9d603-a80e-4b2d-bfb6-8c52a3c8d9dc.mp4

**Comment by gururani-abhishek** [comment]
I have a question regarding this issue, if we'll use the back functionality of Android(back button or swipe back) then the keyboard will go away on it's own. So why do we need to provide extra complexity? just wondering. It's also not a much used feature of our application.
